version: '3.2'
services:
  joybot:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./local-db
        target: /local-db
    container_name: joybot
